
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Profile {
			/**
			* Newsletter consent

				"true" if customer has Newsletter consent
			* 
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#6) 
			*/
			isNewsletter: boolean | null;

			/**
			* Data
			* @group ReachFive - ReachFive
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#13) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#54)
			*/
			data: string | null;

			/**
			* ReachFive request error
			* @group ReachFive - ReachFive
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#20) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#53)
			*/
			reachfiveError: string | null;

			/**
			* Send ReachFive email verification
			* @group ReachFive - ReachFive
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#26) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#50)
			*/
			reachfiveSendVerificationEmail: boolean | null;

			/**
			* Send ReachFive phone verification
			* 
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#32) 
			*/
			reachfiveSendVerificationPhone: boolean | null;

			/**
			* Mark for deletion

				"true" if the customer is marked for deletion in SFCC and Reachfive
			* 
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#38) 
			*/
			toDelete: boolean | null;

		}
		interface SitePreferences {
			/**
			* Authenticated

				Authentication token under Login Form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#61) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#382)
			*/
			authenticated: string | null;

			/**
			* Cartridge name with controllers
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#68) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#347)
			*/
			cartridgeControllersName: string | null;

			/**
			* Active or not default reach five theme 
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#76) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#352)
			*/
			isReach5ThemeActive: boolean | null;

			/**
			* Is Reach Five Enabled
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#83) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#348)
			*/
			isReachFiveEnabled: boolean | null;

			/**
			* is Reach Five Fast Register
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#90) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#357)
			*/
			isReachFiveFastRegister: boolean | null;

			/**
			* is Reach Five Login Allowed
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#97) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#358)
			*/
			isReachFiveLoginAllowed: boolean | null;

			/**
			* Create profile with login as an email or not
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#104) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#359)
			*/
			isReachFiveEmailAsLogin: boolean | null;

			/**
			* Retrieve the provider token in the SFCC session
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#111) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#360)
			*/
			isReachFiveReturnProviderToken: boolean | null;

			/**
			* Session Forced Authentication

				Automatic user authentication from any page
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#118) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#351)
			*/
			isReachFiveSessionForcedAuth: boolean | null;

			/**
			* is Reach Five Transition Active

				Enable the transition state of the Reach Five integration
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#126) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#349)
			*/
			isReachFiveTransitionActive: boolean | null;

			/**
			* Define the API KEY for the Identity API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#134) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#354)
			*/
			reach5ApiKey: string | null;

			/**
			* Define the Client Secret for the Identity API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#141) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#355)
			*/
			reach5ClientSecret: string | null;

			/**
			* Web Core SDK Url

				ReachFive Web Core SDK Url.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#148) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#366)
			*/
			reach5CoreSdkUrl: string | null;

			/**
			* Defaul ReachFive LanguageCode

				Defaul ReachFive LanguageCodes. It sets the language of ReachFive Form. The language lowercase ISO 639-1 code. e.g: en, es, fr, it, nl ... It is used when current site language is not supported.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#157) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#368)
			*/
			reach5DefaulLanguageCode: string | null;

			/**
			* Reach Five Domain
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#166) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#353)
			*/
			reach5Domain: string | null;

			/**
			* Define the API KEY for the Management API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#173) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#361)
			*/
			reach5ManagementApiKey: string | null;

			/**
			* Define the Client Secret for the Management API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#180) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#362)
			*/
			reach5ManagementClientSecret: string | null;

			/**
			* Reach Five Management scope

				Space-delimited list of Management permissions.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#187) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#363)
			*/
			reach5ManagementScope: string | null;

			/**
			* ReachFive profile fields JSON

				ReachFive JSON which contains fields to synchronize and mapping between SFCC and ReachFive profile fields
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#196) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#364)
			*/
			reach5ProfileFieldsJSON: string | null;

			/**
			* Supported ReachFive LanguageCodes

				Supported ReachFive LanguageCodes. They set the language of ReachFive Form. The language lowercase ISO 639-1 codes. e.g: en, es, fr, it, nl ...
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#203) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#367)
			*/
			reach5SupportedLanguageCodes: ReadonlyArray<string> 

			/**
			* Web UI SDK Url

				ReachFive Web UI SDK Url.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#210) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#365)
			*/
			reach5UiSdkUrl: string | null;

			/**
			* Reach Five provider ID
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#219) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#356)
			*/
			reachFiveProviderId: string | null;

			/**
			* Reach Five Transition Cookie Duration

				Duration of the Transition cookie in days. Required to identify the user already migrated to ReachFive.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#227) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#350)
			*/
			reachFiveTransitionCookieDuration: number | null;

			/**
			* Check credentials method

				User Authentication Level Check Settings
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#235) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#369)
			*/
			reachFiveCheckCredentials: EnumValue<'none' | 'password' | null> 

			/**
			* Email editor

				Email update under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#252) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#376)
			*/
			['email-editor']: string | null;

			/**
			* Load social connect

				sdkUiClient Load social connect
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#259) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#370)
			*/
			['load-social-connect']: string | null;

			/**
			* Load social connect login

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#266) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#372)
			*/
			['load-social-connect-login']: string | null;

			/**
			* Load social connect signup

				Social Login under the signup form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#273) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#373)
			*/
			['load-social-connect-signup']: string | null;

			/**
			* Load social connect2

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#280) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#371)
			*/
			['load-social-connect2']: string | null;

			/**
			* Password editor

				Password Reset under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#287) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#375)
			*/
			['password-editor']: string | null;

			/**
			* Phone editor

				Phone update under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#294) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#377)
			*/
			['phone-editor']: string | null;

			/**
			* Re auth container

				Auth token under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#301) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#381)
			*/
			['re-auth-container']: string | null;

			/**
			* Reset password

				Password Reset under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#308) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#374)
			*/
			['reset-password']: string | null;

			/**
			* Social accounts container

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#315) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#378)
			*/
			['social-accounts-container']: string | null;

			/**
			* Ocapi Token Client Id

				The client id/username to get the access token for OCAPI
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#322) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#379)
			*/
			ocapiTokenClientId: string | null;

			/**
			* Ocapi Token Client Password

				The auth password to get the access token for OCAPI
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#329) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#380)
			*/
			ocapiTokenClientPassword: string | null;

			/**
			* Authorize the automatical synchronization of Reachfive

				Authorize the automatical synchronization of Reachfive
			* 
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#336) 
			*/
			ReachfiveAuthorizeSync: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Authenticated

				Authentication token under Login Form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#61) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#382)
			*/
			(name: 'authenticated'): string | null;
			
			/**
			* Cartridge name with controllers
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#68) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#347)
			*/
			(name: 'cartridgeControllersName'): string | null;
			
			/**
			* Active or not default reach five theme 
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#76) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#352)
			*/
			(name: 'isReach5ThemeActive'): boolean | null;
			
			/**
			* Is Reach Five Enabled
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#83) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#348)
			*/
			(name: 'isReachFiveEnabled'): boolean | null;
			
			/**
			* is Reach Five Fast Register
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#90) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#357)
			*/
			(name: 'isReachFiveFastRegister'): boolean | null;
			
			/**
			* is Reach Five Login Allowed
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#97) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#358)
			*/
			(name: 'isReachFiveLoginAllowed'): boolean | null;
			
			/**
			* Create profile with login as an email or not
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#104) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#359)
			*/
			(name: 'isReachFiveEmailAsLogin'): boolean | null;
			
			/**
			* Retrieve the provider token in the SFCC session
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#111) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#360)
			*/
			(name: 'isReachFiveReturnProviderToken'): boolean | null;
			
			/**
			* Session Forced Authentication

				Automatic user authentication from any page
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#118) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#351)
			*/
			(name: 'isReachFiveSessionForcedAuth'): boolean | null;
			
			/**
			* is Reach Five Transition Active

				Enable the transition state of the Reach Five integration
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#126) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#349)
			*/
			(name: 'isReachFiveTransitionActive'): boolean | null;
			
			/**
			* Define the API KEY for the Identity API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#134) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#354)
			*/
			(name: 'reach5ApiKey'): string | null;
			
			/**
			* Define the Client Secret for the Identity API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#141) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#355)
			*/
			(name: 'reach5ClientSecret'): string | null;
			
			/**
			* Web Core SDK Url

				ReachFive Web Core SDK Url.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#148) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#366)
			*/
			(name: 'reach5CoreSdkUrl'): string | null;
			
			/**
			* Defaul ReachFive LanguageCode

				Defaul ReachFive LanguageCodes. It sets the language of ReachFive Form. The language lowercase ISO 639-1 code. e.g: en, es, fr, it, nl ... It is used when current site language is not supported.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#157) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#368)
			*/
			(name: 'reach5DefaulLanguageCode'): string | null;
			
			/**
			* Reach Five Domain
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#166) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#353)
			*/
			(name: 'reach5Domain'): string | null;
			
			/**
			* Define the API KEY for the Management API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#173) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#361)
			*/
			(name: 'reach5ManagementApiKey'): string | null;
			
			/**
			* Define the Client Secret for the Management API
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#180) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#362)
			*/
			(name: 'reach5ManagementClientSecret'): string | null;
			
			/**
			* Reach Five Management scope

				Space-delimited list of Management permissions.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#187) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#363)
			*/
			(name: 'reach5ManagementScope'): string | null;
			
			/**
			* ReachFive profile fields JSON

				ReachFive JSON which contains fields to synchronize and mapping between SFCC and ReachFive profile fields
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#196) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#364)
			*/
			(name: 'reach5ProfileFieldsJSON'): string | null;
			
			/**
			* Supported ReachFive LanguageCodes

				Supported ReachFive LanguageCodes. They set the language of ReachFive Form. The language lowercase ISO 639-1 codes. e.g: en, es, fr, it, nl ...
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#203) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#367)
			*/
			(name: 'reach5SupportedLanguageCodes'): ReadonlyArray<string> 
			
			/**
			* Web UI SDK Url

				ReachFive Web UI SDK Url.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#210) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#365)
			*/
			(name: 'reach5UiSdkUrl'): string | null;
			
			/**
			* Reach Five provider ID
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#219) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#356)
			*/
			(name: 'reachFiveProviderId'): string | null;
			
			/**
			* Reach Five Transition Cookie Duration

				Duration of the Transition cookie in days. Required to identify the user already migrated to ReachFive.
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#227) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#350)
			*/
			(name: 'reachFiveTransitionCookieDuration'): number | null;
			
			/**
			* Check credentials method

				User Authentication Level Check Settings
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#235) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#369)
			*/
			(name: 'reachFiveCheckCredentials'): EnumValue<'none' | 'password' | null> 
			
			/**
			* Email editor

				Email update under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#252) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#376)
			*/
			(name: 'email-editor'): string | null;
			
			/**
			* Load social connect

				sdkUiClient Load social connect
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#259) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#370)
			*/
			(name: 'load-social-connect'): string | null;
			
			/**
			* Load social connect login

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#266) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#372)
			*/
			(name: 'load-social-connect-login'): string | null;
			
			/**
			* Load social connect signup

				Social Login under the signup form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#273) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#373)
			*/
			(name: 'load-social-connect-signup'): string | null;
			
			/**
			* Load social connect2

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#280) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#371)
			*/
			(name: 'load-social-connect2'): string | null;
			
			/**
			* Password editor

				Password Reset under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#287) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#375)
			*/
			(name: 'password-editor'): string | null;
			
			/**
			* Phone editor

				Phone update under the Account Dashboard
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#294) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#377)
			*/
			(name: 'phone-editor'): string | null;
			
			/**
			* Re auth container

				Auth token under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#301) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#381)
			*/
			(name: 're-auth-container'): string | null;
			
			/**
			* Reset password

				Password Reset under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#308) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#374)
			*/
			(name: 'reset-password'): string | null;
			
			/**
			* Social accounts container

				Social Login under the login form
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#315) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#378)
			*/
			(name: 'social-accounts-container'): string | null;
			
			/**
			* Ocapi Token Client Id

				The client id/username to get the access token for OCAPI
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#322) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#379)
			*/
			(name: 'ocapiTokenClientId'): string | null;
			
			/**
			* Ocapi Token Client Password

				The auth password to get the access token for OCAPI
			* @group ReachFive - Reach Five configuration
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#329) | [group](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#380)
			*/
			(name: 'ocapiTokenClientPassword'): string | null;
			
			/**
			* Authorize the automatical synchronization of Reachfive

				Authorize the automatical synchronization of Reachfive
			* 
			* @source [attribute](file:c:\Users\Shadow\source\repos\Reach5\cartridge\CartridgeSFCC\Metadata\site_template\meta\system-objecttype-extensions.xml#336) 
			*/
			(name: 'ReachfiveAuthorizeSync'): string | null;
			
	}
}